### ISSUE TITLE
Create a directory of counties

### ISSUE THREAD

**Issue by newswim** [open-austin/Odyssey-Court-Records-to-JSON#13]
Right now we don't have much information about which counties we can easily collect data from.

We'd like to have:

- [ ] A list of all counties in Texas that use Tyler Technologies (not sure how to find this yet).
- [ ] The version of Odyssey that they're using

The artifact for this could be a Google Spreadsheet, or any other equivalent that lets us easily locate compatible versions for our scrapers and parsers.

**Comment by derac** [comment]
I found this website which is apparently run by Tyler Technologies and seems to list the counties they service:
https://tx.countygovernmentrecords.com/texas/web/

I tried a few different queries, including some inurl stuff, this was the best I could find:
https://www.google.com/search?q=%22Tyler+Technologies%22+%22skip+to+main+content%22+texas+PublicAccess

**Comment by derac** [comment]
list of Texas Counties:
https://gist.github.com/derac/8c48e58beab9df1a4392a6c631b5b85b
