### ISSUE TITLE
Add scraper for Smith County (Tyler)

### ISSUE THREAD

**Issue by newswim** [open-austin/Odyssey-Court-Records-to-JSON#15]
### What makes this county compelling?
* Organizers have started a bail fund there, especially for people who have been identified as mentally ill.
* Has a history of bad court-appointed lawyers

### Resources
Odyssey Homepage - https://judicial.smith-county.com/PublicAccess/default.aspx

**Comment by derac** [comment]
I changed the params a bit, this works currently.
`python3 ./src/scraper.py -county smith`

The parser fails though, needs some work

**Comment by derac** [comment]
Fixed parser issue with Smith county and added exception printing for debugging, should work fine now.
