### ISSUE TITLE
Add scraper for Harris County (Houston)

### ISSUE THREAD

**Issue by newswim** [open-austin/Odyssey-Court-Records-to-JSON#16]
Lots of cool work has been done in Harris county, so it's probably less of a priority overall. At first we thought there wasn't an Odyssey page, but looks like they have one now ([link](https://jpodysseyportal.harriscountytx.gov/OdysseyPortalJP)).

### Resources
Odyssey Homepage - https://jpodysseyportal.harriscountytx.gov/OdysseyPortalJP
District Court (requires login) - https://www.hcdistrictclerk.com/edocs/public/search.aspx

**Comment by derac** [comment]
I don't know the details of what data this returns, but there are alternate methods here under "Downloadable Data Extracts" http://jp.hctx.net/services.htm#gsc.tab=0

**Comment by derac** [comment]
I'm working on compatibility with version 2017+ sites using harris county.

**Comment by derac** [comment]
Here is a minimum scraper for Harris for reference.
```python
import requests

session = requests.Session()

data = {
    "SearchCriteria.SelectedCourt": "Harris County JPs Odyssey Portal",
    "SearchCriteria.SelectedHearingType": "Civil Hearing Types",
    "SearchCriteria.SearchByType": "JudicialOfficer",
    "SearchCriteria.SelectedJudicialOfficer": "63908",
    "SearchCriteria.DateFrom": "03/03/2022",
    "SearchCriteria.DateTo": "03/03/2022",
}

response = session.post(
    "https://jpodysseyportal.harriscountytx.gov/OdysseyPortalJP/Hearing/SearchHearings/HearingSearch",
    data=data,
)

response = session.post(
    "https://jpodysseyportal.harriscountytx.gov/OdysseyPortalJP/Hearing/HearingResults/Read",
)

print(response.text)
```

**Comment by derac** [comment]
Harris scraping is now working, need to work on parsing though 👍🏻
