### ISSUE TITLE
Rename base branch

### ISSUE THREAD

**Issue by newswim** [open-austin/Odyssey-Court-Records-to-JSON#18]
Right now this branch is called `master`, I'd suggest we rename it to `main`. This seems to be the most popular alternative. It's substantially easier to make this change now, before there are a lot of branches and open PRs.

Github's statement: https://sfconservancy.org/news/2020/jun/23/gitbranchname

More info on Github's own policy here: https://github.com/github/renaming

**Comment by derac** [comment]
I don't appear to have the perms to do this, but https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by derac** [comment]
Who has permission to do this?

**Comment by newswim** [comment]
Hm, that's odd! Right now you have the `Maintain` access right.

https://github.com/open-austin/Odyssey-Court-Records-to-JSON/settings/access

I went ahead and updated this. Default branch is now `main`.

**Comment by derac** [comment]
can't get there
