### ISSUE TITLE
Gather data to pinpoint a JO and day for each county which definitely returns cases for testing.

### ISSUE THREAD

**Issue by derac** [open-austin/Odyssey-Court-Records-to-JSON#25]
It would be nice to have a list of JO/day for each county which could be used when calling scraper to test and make sure that it can pull down HTML case data quickly. Running counties with default settings often returns many 0 case results, so deeper code paths are not being hit. With this info we could automate testing and reporting on how many sites are working/not working.

The easiest way to do this would be to
 1. Go to each portal in https://github.com/open-austin/Odyssey-Court-Records-to-JSON/blob/master/resources/texas_county_data.csv
 2. Select Court Calendar > Search by JO > select any JO
 3. Select a very wide date range
 4. Find any date a case was returned on
 5. list county, JO, date

**Comment by derac** [comment]
The data can be input here, you just need to make a new test and fill in the county, date, and judicial officer.
https://github.com/open-austin/Odyssey-Court-Records-to-JSON/blob/master/test/full_e2e.py

When searching for a good date and judicial officer, try to find one with as few results returned as possible to speed up testing.

**Comment by serendipity-211** [comment]
@derac Have you been following any of the TylerTechnologies stuff that came up first out of California? [https://www.law.com/therecorder/2022/03/07/defense-lawyers-demand-state-bar-disclose-more-info-about-data-breach/](https://www.law.com/therecorder/2022/03/07/defense-lawyers-demand-state-bar-disclose-more-info-about-data-breach/) 
With some of the changes they seem to be making now to their system, will this still work going forward? Thx in advance & apologies for the total beginner question

**Comment by mscarey** [comment]
@serendipity-211 not sure if there will be any change in the Texas county websites. Probably every agency with a Tyler website is using it a little differently. Those that have been using them exclusively to publish public data probably won't see a need to redesign.

**Comment by derac** [comment]
> @derac Have you been following any of the TylerTechnologies stuff that came up first out of California? https://www.law.com/therecorder/2022/03/07/defense-lawyers-demand-state-bar-disclose-more-info-about-data-breach/ With some of the changes they seem to be making now to their system, will this still work going forward? Thx in advance & apologies for the total beginner question

Thanks, yeah I'm aware of it. I assume this is the Judyrecords issue? What happened in that case is that Judyrecords found that they could scrape the new version of odyssey by enumerating case records by number directly. In doing so, they exposed a flaw in the software where there are no access controls on records. They ended up scraping public records. We're not doing that here, so we're good.

**Comment by serendipity-211** [comment]
> @serendipity-211 Thanks, yeah I'm aware of it. I assume this is the Judyrecords issue? What happened in that case is that Judyrecords found that they could scrape the new version of odyssey by enumerating case records by number directly. In doing so, they exposed a flaw in the software where there are no access controls on records. They ended up scraping records that were "supposed to be secret". We're not doing that here, so we're good.

Would it be possible to use this for a state outside of Texas (whose court portal appears to function similarly to the Texas ones)? If so, is there any chance I can ask you some specific questions regarding that. As I said, and painfully obvious, I’m a total beginner but abs. looking to learn more and to try and use this. TIA

**Comment by derac** [comment]
Wrong venue for this line of conversation. Please contact me out-of-band with personal concerns.

**Comment by salmanv12** [comment]
Hi there, new to github. I'm looking for something similar to this. Not a whole lot of coding experience but I was wondering if it was complete or if I can help contribute anyway?

**Comment by derac** [comment]
Complete thanks to @dakotacbrown ! Will need further analysis on the portals that are failing, good comments left by Dakota in the e2e test file.
