### ISSUE TITLE
find enough data for research question

### ISSUE THREAD

**Issue by mscarey** [open-austin/Odyssey-Court-Records-to-JSON#8]
The group was planning to look at Hays County first. There was a major change point in Hays around 2002. That's when the law changed to provide more resources for appointed attorneys. There was a research question about whether the change in funding improved outcomes.

There's not a lot of historical data before 5 or 10 years ago. There are only a few data points before 2014 or 2015.

**Comment by derac** [comment]
Is this being tackled outside this forum? Should I close this to clear the Issue log?

**Comment by normaljosh** [comment]
Yep, this can be closed, issue turned out to be on the job scheduler side.
